apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template: # Blueprint/Main Configuration for Pods
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017

          env: # Ist eine Liste von Umgebungsvariablen
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-password
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  type: ClusterIP # default
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017 # selbst bestimmbar
      targetPort: 27017
